server:
  port: 8888

name: wangwu
#  对象
person:
  name: zhangsan
  name2: ${name} #引用name1的值
  age: 27
  address:
    - beijing
    - shanghai

# 对象行内写法
person2: {name: lisi,age: 12}

#数组
address:
  - beijing
  - shanghai

#数组行内写法
address2: [beijing,shanghai]

#纯量
msg1: 'hello \n word' #不会识别转义字符
msg2: "hello \n word" #会识别转义字符